version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.0
  shellcheck: circleci/shellcheck@3.1

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/review
      - shellcheck/check
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          orb_name: nativeedge-plugins-orb
          requires: [orb-tools/lint, orb-tools/pack, orb-tools/review, shellcheck/check]
      - orb-tools/publish:
          orb_name: circleci/aws-ecr
          vcs_type: << pipeline.project.type >>
          pub_type: production
          context: orb-publisher
          requires: [orb-tools/pack]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
